### ISSUE TITLE
X10 not defined

### ISSUE THREAD

**Issue by mahadevramule** [hbi99/defiant.js#100]
its giving me error at x10.compile in JSON.toxml function that 
x10 is not defined

**Comment by hbi99** [comment]
Hi @mahadevramule,
Can you examplify with code please?

**Comment by mahadevramule** [comment]
![untitled1111](https://user-images.githubusercontent.com/42061242/45199592-30472500-b28a-11e8-8d98-2a972c279c51.png)

x10 is not defined

**Comment by hbi99** [comment]
I know how my code looks like. I dont know what you have written. So examplify your code

**Comment by mahadevramule** [comment]
i used it like this
![untitled2222](https://user-images.githubusercontent.com/42061242/45213498-5635ef00-b2b5-11e8-9ba4-d50fc9fcac71.png)

**Comment by mahadevramule** [comment]
hey can i give you merge request for that changes

**Comment by hbi99** [comment]
Have you tested it both in browser and node? I cant tell what you added or removed...screenshot of a minified file is no-go

**Comment by mahadevramule** [comment]
i just added x10 in defiant.min.js file and window.URL || window.webkitURL
