### ISSUE TITLE
NodeJS XML <-> JSON

### ISSUE THREAD

**Issue by gtamas** [hbi99/defiant.js#110]
Hi

Would it be possible to export the following APIs as well: 

Defiant.xmlFromString(xml_string) 
Defiant.node.toJSON()

We could then convert XML to JSON and JSON to XML. I'm mostly interested in the former.
There are several conversion libs, but they produce JSON formats not fully compatible with Defiant's Xpath syntax, therefore some stuff cannot be queried at all. 
So it would be better to use Defiant's own tool for this. Either that or I have to use a post-processor to format the JSON properly.

Please let me know if this is possible? Would those 2 functions work in the Node env?

**Comment by gtamas** [comment]
Btw, if you don't wanna export these or they are not suitable for node right now, what library would you recommend?

I need something that allows Xpath to work properly. But my current JSON converter puts attributes in to '$': {...} objects, stores node values under '_' keys ... etc. It's useless. Queries either can't find anything or they return partial results..

**Comment by gtamas** [comment]
I've found a solution to do it with my current JSON lib, so I'm closing this, but I still think that making the browser and the nodeJS API identical (well, as much as possible) would be useful.

**Comment by hbi99** [comment]
Well, since I wrote this library the idea to export those methods has crossed my mind ;-) There is a reason to their absence; XML nodes does "not exist" in node-context. Had they been, there would be no need for puppeteer at all :-)
