### ISSUE TITLE
Not able to find values with &

### ISSUE THREAD

**Issue by xlplugins** [hbi99/defiant.js#111]
Hi, 

We are facing an issue where we are unable to make defiantjs work with the values having "&". 

Here we made a fiddle, please check: http://jsfiddle.net/hbf7euv5/

**Comment by hbi99** [comment]
@xlplugins 
Thanks for the feedback...a fix is on the way in next release.
Probably this evening

**Comment by hbi99** [comment]
This issue is solved in `v2.1.4`
