### ISSUE TITLE
Chrome 70 breaks JSON.search

### ISSUE THREAD

**Issue by Adamant22** [hbi99/defiant.js#112]
Please ignore!

**Comment by hbi99** [comment]
Is there any chance I can see you JSON data - or at least; is it very large?
Also, I am about to release `v2.2.0` - do you mind testing it with that version?

**Comment by Adamant22** [comment]
My apologies. I guess my Edge test was using cached data. Once I cleared it, it started happening there too.




Turned out to be a data issue (too many recursive properties). I massaged the incoming data and all is fine. I'll remove the issue.




And thanks for the awesome tool! 




Adam Schlager 







On Thu, Jan 10, 2019 at 3:18 PM -0600, "Hakan Bilgin" <notifications@github.com> wrote:












Is there any chance I can see you JSON data - or at least; is it very large?

Also, I am about to release v2.2.0 - do you mind testing it with that version?
