### ISSUE TITLE
Split packet so npm users don't need to install pupeteer on pure browser installation

### ISSUE THREAD

**Issue by napalu** [hbi99/defiant.js#115]
Would be nice for those of us using npm as a package manager for our browser-based development to have an npm package which does not pull puppeteer on install.

**Comment by hbi99** [comment]
Thanks for the feedback...looking in to this

**Comment by hbi99** [comment]
Hi again @napalu,
So I've been looking around regarding this but haven't found a good guideline / example. Do you have any suggestion or point to a direction to resolve this issue?

Thanks in advance

**Comment by napalu** [comment]
Hi @hbi99 I was thinking it could be split in 2 packages.
1. defiant.js-all (nodejs dependencies + defiant.js)
2. defiant.js (or defiant.js-core) for browsers

It would mean maintaining two separate package builds. I'll try to see if there's an easier way but right now nothing comes to mind.

**Comment by hbi99** [comment]
Hi @napalu,
Splitting into 2 packages does not sound appealing - even though I am considering it as an option.
I'll research more to see how others might have solved it.

Meanwhile, can you give me a gist of your npm commands, when installing packages for browser environment?

Thanks in advance

**Comment by hbi99** [comment]
Since, I am not getting feedback on this issue, I am closing it. Re-open it if you want to pursue this issue.

**Comment by tomyun** [comment]
I'm stuck with the same issue as OP. Do we have any solution yet?

**Comment by simonguillen** [comment]
Any solution on this? I wanted to implement this on React but I seem to encounter issues with Puppeteer  being unable to run on a React app.

https://stackoverflow.com/questions/60700861/cant-run-puppeteer-in-react-app-module-not-found-cant-resolve-ws-when-comp

Hope this issue gets reopened.

**Comment by hbi99** [comment]
I removed puppetter support in v2.2.8
Does it help?
