### ISSUE TITLE
no search result, if first letter capital Ä (umlaut)

### ISSUE THREAD

**Issue by paddle07** [hbi99/defiant.js#124]
Hi, I noticed that code defiant.search(snapshotPraxen, '//*[contains(name,"'+searchTerm+'")]'); doesn't find any results if the searchterm/name starts with a capital umlaut (Ä, Ö, Ü). Lowercase umlaut in the name seem to work.

**Comment by hbi99** [comment]
Hi @paddle07,
Thanks for bringing this to my attention.
This issue has been fixed in version 2.2.7

Cheers
