### ISSUE TITLE
find parent using recursion

### ISSUE THREAD

**Issue by Scnck** [hbi99/defiant.js#125]
what is the best method of finding a parent object based on "key" rather than /.. for one level  my results maybe returned from different object levels... be I want to return the main root parent.

**Comment by hbi99** [comment]
Hi @Scnck,
There is at least two ways to do this (that I know of). These methods uses the XPath Evaluator at https://www.defiantjs.com/
The first one is this - enter the following XPath in the input field:
```
//store[.//isbn]/bicycle
```
...this "tells" that we are looking for the __store__ node and make a sub-query with "[...]". In this case I added that I want to make further search with __store__ as "base".

The second one is this:
```
//@price[ancestor::book//category = "fiction"]
```
...this "tells" that we want __@price__ but only if it's __ancestor__ is "book" and __@price__ are among the one with category of "fiction". With "//", the query is looking for matches that is regardless of "depth" - meaning "category" and "@price" does not need to be on the same level in depth if the data structure.

I hope this helps. I would like to suggest that you cut and paste part of your JSON data in to the Evaluator by clicking the "pen". This way you can experiment your way to the right query you are looking for. I am closing this issue - re-open it, if you need further assistance.
