### ISSUE TITLE
Defiant not returning results for large json data

### ISSUE THREAD

**Issue by janaraj** [hbi99/defiant.js#22]
I tried defiant and the search with xpath works great, but when the data is huge it's not going all the way till the end, I think its getting broken somewhere inbetween, The data that I tried was of 500KB.

**Comment by hbi99** [comment]
@janaraj Are your sure?
Do you have any example code online to prove your claim?

In the demo folder found here;
https://github.com/hbi99/defiant.js/blob/master/demo/json-search-4.htm
...a search is made on 1.6MB large JSON file. The search exemplified in that file returns 1129 matches and includes the last one as well as the first one in the JSON structure.

If you have files online, I can help you troubleshoot your code.
Cheers
