### ISSUE TITLE
xpath evaluator highlighting error on defiantjs.com

### ISSUE THREAD

**Issue by prushforth** [hbi99/defiant.js#27]
Hi,  Your project looks really interesting.  Just to let you know I was trying out the xpath evaluator on http://defiantjs.com/#xpath_evaluator and found that the highlighting was wrong for xpaths that I cooked up myself, for example //book/category seems to only highlight 2 of the 4 books, although I can see they all have a category property.  I did try the expression in the console and it worked correctly, so I suppose it is just a highlighting problem.

Nice work!

Cheers,
Peter

**Comment by hbi99** [comment]
Thanks Peter!
Yeah...this is a known issue and fixing this is on my to-to list. I'll get back on this as soon as it's done.
As you put it, this is not a bug with defiant itself - it's just a highlighting / UI related bug.

I'm currently adding a feature utilizing web worker, making the experience even smoother with large JSON structures. I'll try to solve this issue along with the ww-feature.

**Comment by prushforth** [comment]
Hi Hakan,

I noticed (almost immediately after hitting ‘submit’ ☺) that someone else had entered the same issue sort of.

Anyway, I thought it might deter some people from trying your library, even though it doesn’t appear to me to be a bug in the library, which I think is a great idea BTW.

Good luck!

Cheers,
Peter
