### ISSUE TITLE
Unexpected behavior when using multiple conditions

### ISSUE THREAD

**Issue by BlackWiCKED** [hbi99/defiant.js#33]
I have spotted something strange when trying to connect multiple conditions with OR operator.

Demonstration of the issue:

XPATH EVALUATOR with default data:

**//*[contains(title, "The") or contains(author, "Evelyn")]**
Returns only 2 items - those which have the word "the" in their title.

**//*[contains(title, "The") or contains(author, "velyn")]**
Surprisingly it works when I delete the first character from the author condition.
All 3 items are returned in this case.

Must be some kind of problem with the regex replace. I will try to locate and fix it.

**Comment by hbi99** [comment]
Hi @BlackWiCKED,
Thanks for the issue...actually, there is an regexp that automatically changes contains to case-insensitive. Look at this file;

https://github.com/hbi99/defiant.js/blob/master/src/string.js

I can fix this in a couple of hours...

**Comment by BlackWiCKED** [comment]
Actually, looks like it was easier to find than I thought. There is only one missing **/g** in the replace function to replace all occurrences of contains(). It works now.

https://raw.githubusercontent.com/hbi99/defiant.js/master/dist/defiant-latest.js

```
**/contains\(([^,]+),([^\\)]+)\)/g**
```

```
if (!String.prototype.xTransform) {
	String.prototype.xTransform = function () {
		var str = this;
		if (this.indexOf('translate(') === -1) {
			str = this.replace(/contains\(([^,]+),([^\\)]+)\)/g, function(c,h,n) {
				var a = 'abcdefghijklmnopqrstuvwxyz',
					q = n.trim().slice(-1);
				return "contains(translate("+ h +", "+ q + a.toUpperCase() + q +", "+ q + a + q +"),"+ n.toLowerCase() +")";
			});
		}
		return str.toString();
	};
}
```

**Comment by BlackWiCKED** [comment]
Shall I send a proper pull request? I have not forked the original repository yet.
