### ISSUE TITLE
Sorting results

### ISSUE THREAD

**Issue by samsonkhisty** [hbi99/defiant.js#36]
Greetings Hakan,
My current xpath query is like so 

    //*[contains(title,"century") or contains(title,"honour")]

If I run this in the online xpath evaluator, it highlights the correct records, but the returned object will return in the same order the JSON is in. So in the above example, I want "Sayings of the Century" to be returned as the first object and then "Sword of Honour" as the next object. Is this possible at all?

**Comment by samsonkhisty** [comment]
To elaborate more: 

I am currently using defiant for search results in type ahead. I am doing searches on one field only. The field is called raw_content and it has a concatenation of title and description. So If the user searches for a string like 'manage a project', I want the very first result to be the closest match followed by any of the words that match. 

I use the following logic: 
1: build first query,  //*[contains(title,"manage a project'") 
2: break down the string and remove common words. so I get manage,  project and build a query using contains
3: My final query is 

    //*[contains(raw_content, "manage a project ") or contains(raw_content, "manage") or contains(raw_content, "project")]

What is happening is, the json object that contain the exact string is last in the results because that is how it is in the JSON object. So what I want is show the results exactly in the order of my xpath query.

**Comment by hbi99** [comment]
Generally, selection and sort ordering are different processes. XPath as only a language to express the querying and not ordering; http://www.w3.org/TR/xpath/

Additionally - sorting is really trivial in javascript and very little code is required to make custom sort-functions.
