### ISSUE TITLE
Any way to return multiple attributes or concat 2 attributes and return as a single value

### ISSUE THREAD

**Issue by samsonkhisty** [hbi99/defiant.js#37]
For eg. 

    JSON.search(snapshot, "//article_id | //title") 

returns array like ["123","article1 header", "345" ," article 2 header", ...], 
I tried using concat so I could return both values as one string and work from there but that fails.

**Comment by samsonkhisty** [comment]
For now I have a workaround using underscore library, Couldn't find better solution with XPath. Hoping you would know.   

          arr1 = JSON.search(snapshot, "//article_id")
          arr2 = JSON.search(snapshot, "//title")
          title_lookups = _.object(arr1, arr2)

**Comment by hbi99** [comment]
Would it work with something like:

```
JSON.search(snapshot, "//*[article_id or title]")
```

**Comment by samsonkhisty** [comment]
article_id and title is present in all items of my JSON object. 
The above query returns me the full object. I just wanted to extract just the 2 attributes. Either that or then return one value that is concatenated. I wasn't able to achieve both so I continued the workaround, which works but isn't clean in my opinion.

**Comment by hbi99** [comment]
I see...XPath and this lib only searches JSON structure. Altering the results would not be preferable. IMHO, auto-concatenation is not a common use-case....don't you think?

**Comment by samsonkhisty** [comment]
I concur on auto-concatenation, I resolved it with getting the full object
using your query. You can close this ticket.

*---*
*Samson Khisty*
Manager, Design

<http://eightspokes.com/>
617.678.9802 I @eightspokes
www.linkedin.com/in/skhisty/

*NOTICE TO RECIPIENT:* If you are not the intended recipient of this
e-mail, you are prohibited from sharing, copying, or otherwise using or
disclosing its contents. If you have received this e-mail in error, please
notify the sender immediately by reply e-mail and permanently delete this
e-mail and any attachments without reading, forwarding or saving them.
