### ISSUE TITLE
Xpath query issue multiple words

### ISSUE THREAD

**Issue by samsonkhisty** [hbi99/defiant.js#38]
Hi there, 
Couldn't find anything online, just putting it here for exposure. 

    JSON.search(snapshot,'//*[contains(title, "manage") and contains(title, "project")]')
    JSON.search(snapshot,'//*[contains(title, "manage project")]')

The second query returns me 1 object while the first one doesn't for some unknown reason. 
Check attached image, see title for returned object. 
![screen shot1](https://cloud.githubusercontent.com/assets/3254606/6586867/c06a83e6-c753-11e4-9e8f-1427fa9070e9.png)

**Comment by hbi99** [comment]
If you try this xpath in XPath Evaluator (at http://www.defiantjs.com), you'll see that there is a match:

//*[contains(title, "the") and contains(title, "lord")]

Which version of DefiantJS are you using? If not the latest, try updating your version of the lib.
Also, have a look at https://github.com/hbi99/defiant.js/issues/33

**Comment by hbi99** [comment]
@samsonkhisty - how are you doing with this issue?
Can I close it?

Cheers

**Comment by samsonkhisty** [comment]
Hi @Hakan, I didn't get a chance to test with the new version yet. You can
close this for now. I will test and get back by next week.

*---*
*Samson Khisty*
Manager, Design

<http://eightspokes.com/>
617.678.9802 I @eightspokes
www.linkedin.com/in/skhisty/

*NOTICE TO RECIPIENT:* If you are not the intended recipient of this
e-mail, you are prohibited from sharing, copying, or otherwise using or
disclosing its contents. If you have received this e-mail in error, please
notify the sender immediately by reply e-mail and permanently delete this
e-mail and any attachments without reading, forwarding or saving them.
