### ISSUE TITLE
ios memory usage

### ISSUE THREAD

**Issue by baseio** [hbi99/defiant.js#39]
Hi,
Thanks for the excellent work! Go Sweden!

Im using v. 1.2.8 to create a webworker snapshot.
Completes in about 12 secs (its a 10MB JSON file), and performs great.
I then packed up the app with cordova (for iOS), and watched memory usage peak above 600MB when the lib attempts to return the snapshot from the webworker to the main thread. 
(At least, thats where I think the problem occurs).
This makes iOS call the applicationDidReceiveMemoryWarning, and then the app crashes :-(
Works fine in the simulator (which is not limited on RAM).

Ideas?

Best,

j.

**Comment by hbi99** [comment]
Woww...I've not even tried using the lib with that large file. Cool that it works. Currently I have no idea what might cause the crash but I'll try experimenting and see if I can find any solution.

**Comment by baseio** [comment]
cool ;-)
Let me know if I can help with a repo-case or sth. Godspeed!

**Comment by hbi99** [comment]
@baseio - I have been experimenting but I do not have any suggestions yet. To be honest, I didn't intend DefiantJS to be a "heavy-lifter"...the largest files I have tested with has been a few megabytes in size.

Anyone else have any suggestions?

**Comment by robhawkes** [comment]
Theoretically, the Web Worker can pass back the processed data with a tiny overhead by utilising [transferrable objects](http://updates.html5rocks.com/2011/12/Transferable-Objects-Lightning-Fast). It requires some extra modifying of the original data though, so it may not be useful in this case. It makes a massive difference.

**Comment by hbi99** [comment]
Transferable objects seems to be one way to go. Though transferable objects and this issue is more of an issue that belongs to the *[x10js](https://github.com/hbi99/x10.js)* library that I'm using for DefiantJS.
I am closing this issue and opening the issue at *x10.js*
