### ISSUE TITLE
Less than / greater than operators on strings

### ISSUE THREAD

**Issue by tmld** [hbi99/defiant.js#40]
Hi,

Is there any way to do less than / greater than comparisons on string values? E.g. (This doesn't return any results):
    //book[isbn > "0-300-00000-0"]

Many thanks,

Toby.

**Comment by hbi99** [comment]
I don't think it is possible to do this in XPath 1.0 (which is the version supported in all browsers). In v2.0 there are a lot more interesting and usable stuff. Hopefully the browsers will take the leap to the next version soon.

**Comment by tmld** [comment]
Oh, what a shame. Come on browsers!

Thanks for letting me know.
