### ISSUE TITLE
JSON<>XML attributes prefix

### ISSUE THREAD

**Issue by untemps** [hbi99/defiant.js#41]
Currently, there is no way to change the prefix ('@') of the XML attributes during the JSON conversion.
Use the '@' is quite painless when we have to manipulate the corresponding JSON property in Javascript.
It would be great to add a setter for the prefix string.

**Comment by hbi99** [comment]
I think changing prefix might be a mistake...the reason is that the "@" is the character used in XPath expressions. Therefore, the prefix should correlate - unless I misunderstand your point. Can you elaborate with code perhaps?

**Comment by untemps** [comment]
Sure.
If I try to manipulate the JSON @-prefixed properties in Javascript, like json.@prop, a 'Unexpected token ILLEGAL' exception is raised.
I can get around this issue by using the eval expression json['@prop'] but, in one hand, it's quite ugly, on the other I can't use some HTML AngularJS' data-binding expressions, like ng-class="'{{json['@prop'] | filter}}'".
What do you think?

**Comment by hbi99** [comment]
I don't feel I've enough information to make alteration for this issue. Until further, I'm tagging this issue with "wont fix" but eventually, this might change.
