### ISSUE TITLE
Elements with value=0

### ISSUE THREAD

**Issue by sebglx** [hbi99/defiant.js#43]
Hi,
Thanks for the awesome work :)

I've encountered a weird behaviour on objects with value=0, which I believe is a bug:

```
a = {"obj": {"four": 4, "zero":0, "zerodotone":0.1}}
JSON.search(a, "//zero")
> []
```

Whereas it works fine for every other number:
```
a = {"obj": {"four": 4, "zero":0, "zerodotone":0.1}}
JSON.search(a, "//zerodotone")
> [0.1]
```

This is a bit confusing because a search on a non-existing key also returns [], making it just like if my "zero" object does not exist.
```
a = {"obj": {"four": 4, "zero":0, "zerodotone":0.1}}
JSON.search(a, "//zero")
> []
JSON.search(a, "//notexistingkey")
> []
```

**Comment by hbi99** [comment]
@sebglx 
Great catch...thanks for the report.
This is now fixed in v1.3.0
