### ISSUE TITLE
Trying to paginate the snapshot

### ISSUE THREAD

**Issue by colinory** [hbi99/defiant.js#46]
Thanks for this great library. I'm trying to use

[position() >= 10 and not(position() > 20]

to paginate/limit the result. 

What's the right syntax? Thanks!

**Comment by hbi99** [comment]
Hi @colinory 
Try with the following expression.
```
//book[position() > 1 and position() < 4 ]
```

This expression works in XPath Evaluator at [DefiantJS.com](http://www.defiantjs.com). The reason for the integers of 1 and 4 is due to the limited data in the evaluator. To try it, just paste it in the input field.

Thanks for using DefiantJS :-)

**Comment by colinory** [comment]
Ok, I'm using DefiantJS in combination with the Wordpress API. The WP-API JSON output is different then the example in the XPath Evaluator. The post itself doesn't have a name as identifier. You just use the index to loop through an array. 

Example of 10 Wordpress posts > https://jsonblob.com/5551ff82e4b0b306c890a7d1

I need to query through a lot of posts and for example query based on a location. This is working with DefiantJS. But I can't get it working with your pagination example.

>> Retrieve posts by 2 locations:
//*[contains(locations,"saba") or contains(locations,"curacao")]/..

Can you please help me? Thanks!

**Comment by colinory** [comment]
Solved it! I've added this:

{ "wordpress": {
"posts":[]
}}
