### ISSUE TITLE
DefiantJS in combination with the Wordpress API

### ISSUE THREAD

**Issue by colinory** [hbi99/defiant.js#47]
I'm using DefiantJS in combination with the Wordpress API. The WP-API JSON output is different then the example in the XPath Evaluator. The posts itself doesn't have a name as identifier. You just use the index to loop through an array. 

Example of 10 Wordpress posts > https://jsonblob.com/5551ff82e4b0b306c890a7d1

I need to query through a lot of posts and for example query based on a location. This is working with DefiantJS. But I can't get it working with your pagination example.

>> Retrieve posts by 2 locations:
//*[contains(locations,"saba") or contains(locations,"curacao")]/..

Can you please help me? Thanks!

**Comment by hbi99** [comment]
Hi @colinory,
The correct expression in your scenario is something like this:

```
//*[contains(./acf/locations/name, 'saba') or contains(./acf/locations/name, 'curacao')]
```

__Caution:__ your JSON contains some unescaped characters - for instance in the "Curacao" name. This makes the curacao post not be in the found array. So you need to either escape correctly or (not good solution but) search on the slug-property...like this:

```
//*[contains(./acf/locations/slug, 'saba') or contains(./acf/locations/slug, 'curacao')]
```

Let me know how this turns out for you.

Cheers

**Comment by hbi99** [comment]
I added a new feature to the site...follow [this link](1) to see XPath Evaluator **with your data** and example XPath expression that applies your data...

[1]: http://defiantjs.com/#xe_xpath=//*[contains(./acf/locations/name, 'saba')]&xe_src=https://jsonblob.com/api/jsonBlob/5551ff82e4b0b306c890a7d1)

**Comment by colinory** [comment]
cool! but it doesn't seems to work though..

**Comment by hbi99** [comment]
@colinory 
Which browser are you using? I tested it with Firefox & Chrome - works like a charm. It should look something like this;
![image](https://cloud.githubusercontent.com/assets/637727/7616360/0b7461d6-f9a4-11e4-8bbc-2c5cd4091c49.png)

**Comment by colinory** [comment]
Yes it's working. Thanks! Cool feature. - Caching issue I guess.

Other question:

When I search the snapshot I append the result to the DOM. BUT to prevent duplicate items in the DOM I want to remove the items from my JSON object. On this way I'm able to create a new snapshot and search it again, without retrieving the same items as the first time. 

Do you know an easy way to remove these items from the JSON object?

**Comment by colinory** [comment]
Or even better.. remove the items from the SNAPSHOT. Is this possible?

**Comment by hbi99** [comment]
@colinory 
Check out this StackOverflow entry;
http://stackoverflow.com/questions/2812122/distinct-in-xpath

With XPath 1.0, there seems ways to distinct matches.

**Comment by colinory** [comment]
Thanks! And do you know how to ORDER BY? (hopefully with 2 values) - 'PINNED TO TOP' & 'DATE'

**Comment by colinory** [comment]
I'm having trouble finding the second(etc.) slug in the specialty array. It only finds the first value:

//*[contains(./acf/location/slug,"curacao") and contains(./acf/specialty/slug,"dispute-resolution")]

https://jsonblob.com/5554ce28e4b0ca118fcd2f25

**Comment by colinory** [comment]
Hi I'm having trouble search for the second specialty in the JSON object. Your example from a few days ago only searched for the first value in the array

http://defiantjs.com/#xe_xpath=//*%5Bcontains(./acf/specialties/slug,'dispute-resolution')%5D&xe_src=https://jsonblob.com/api/jsonBlob/5551ff82e4b0b306c890a7d1

**Comment by hbi99** [comment]
Not sure what might be wrong but this expression catches all three...

```
//*[contains(.//slug,'dispute-resolution')]
```

http://defiantjs.com/#xe_xpath=//*%5Bcontains(.//slug,'dispute-resolution')%5D&xe_src=https://jsonblob.com/api/jsonBlob/5551ff82e4b0b306c890a7d1

**Comment by colinory** [comment]
This seems to work > //*[contains(.//slug/..,'dispute-resolution')]

BUT! But I need to search the exact column. And this query is looking for every slug in the whole OBJECT.

I need a query that is searching for specialty_lead/slug and not specialty/slug. This is the JSON object I need to search: https://jsonblob.com/5554ce28e4b0ca118fcd2f25

Thanks!

**Comment by colinory** [comment]
I think I've got it > //posts/acf/specialties[slug='corporate']/../..

**Comment by colinory** [comment]
I've got it > (//posts/acf[specialties/slug='corporate' and locations/slug='st-eustasius'])/..

**Comment by hbi99** [comment]
Cool 😊
