### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by ethan-sletteland** [hbi99/defiant.js#50]
Hello, not sure what the deal is, but right now bower is pulling down 1.2.6 as the latest (should be 1.3.1), and the "-latest" file is 1.2.5 (https://github.com/hbi99/defiant.js/blob/master/dist/defiant-latest.js) while defiant.js is 1.3.1 (https://github.com/hbi99/defiant.js/blob/master/dist/defiant.js)

**Comment by hbi99** [comment]
@ethan-sletteland 
Thanks for the issue...I've created a new release and added a bower package manifest.

Please let me know that it plays well on your end now
Cheers
