### ISSUE TITLE
IE 9 - 10  ActiveXObject is undefined Error

### ISSUE THREAD

**Issue by marruendarol** [hbi99/defiant.js#53]
I was trying to emulate explorer 9-10 from windows 10 / edge  and i a m getting SCRIPT5009: 'ActiveXObject' is undefined

i am using 1.3.1v 
is there anything i can do , or its the intended if tested on emulator?

**Comment by hbi99** [comment]
@marruendarol 
Just returned from vacation :-)

Do you have this meta-tag in your header?
<meta http-equiv="X-UA-Compatible" content="IE=10">

Unfortunately, IE10 has dropped XML/XPath support they had in earlier versions but using this quirk, the support is re-enabled (no idea what MS logic is...not sure if they know it themselves).

**Comment by marruendarol** [comment]
Thank you hbi99, do you mean this one ? 
<meta http-equiv="X-UA-Compatible" content="requiresActiveX=true"/>

**Comment by hbi99** [comment]
Apologize...forgot to encapsulate the HTML code with proper markdown :-)
Below is the meta tag:

```html
<meta http-equiv="X-UA-Compatible" content="IE=10">
```

**Comment by marruendarol** [comment]
Neither IE=10 or requiresActiveX meta-tags are working on IE  9,10,11   :(,   at least not on EDGE emulator i have to test it on a real IE.

Error Description:
X Script5009 'ActiveXObject' is undefined  - defiant.min.js (9,3479)

Thank you in advance.

**Comment by hbi99** [comment]
Thats weird...I am using VirutalBox on MacOS Xm Win7 + IE11...when testing out;
http://www.defiantjs.com

...and XPath Evaluator, it all works just fine.

**Comment by marruendarol** [comment]
i am starting to believe that the problem is IE Edge Emulator because   defiantjs.com gives me the same error when testing on it 
![image](https://cloud.githubusercontent.com/assets/470392/9224209/5f546328-40c6-11e5-8c6b-369c35ee45b3.png)

**Comment by hbi99** [comment]
I am closing this issue, if you don't mind.

Cheers

**Comment by priyadeshmukh15** [comment]
Hi,
I am also getting the same error for IE11, tried adding 
`<meta http-equiv="X-UA-Compatible" content="IE=11">`

But it does not work in my case.
**Error I am getting is: 
Object doesn't support property or method 'selectNodes'**
on Line :  console.log(JSON.search(exampleJson, '//*["]'));

**Comment by jarben** [comment]
Looks like this only happens in on Windows 8+ where ActiveXObject is no longer available even if the compatibility meta tag is used: 

[There is no solution to this problem. As of IE11 on Windows 8, Microsoft no longer allows ActiveX plugins to run in its browser space. There is absolutely nothing that a third party developer can do about it.
](http://stackoverflow.com/questions/26151999/ie11-prevents-activex-from-running)

To fix this issue in defiant.js, just replace: 

![image](https://cloud.githubusercontent.com/assets/561365/17014806/ebc9833c-4f26-11e6-9ef5-76b71bd09a2b.png)

by: 

![image](https://cloud.githubusercontent.com/assets/561365/17014816/f785f606-4f26-11e6-8eef-65ad0dcd6313.png)

**Comment by hbi99** [comment]
Done...thanks for the tip
