### ISSUE TITLE
Creating snapshot too slow

### ISSUE THREAD

**Issue by krishnakowshik** [hbi99/defiant.js#57]
Hi,
How long does it take a snapshot for a JSON of 500KB ? It takes around 30 minutes for me.
ALso, the web worker thing does not seem to be working for me, as the UI is being blocked. Any ideas on this?

Thanks.

**Comment by hbi99** [comment]
Hi @krishnakowshik,
500KB data should be processed in a few seconds and in a dedicated thread.

Is your code accessible for me to look at, online somewhere?
If not, perhaps, you can put it online at JSFiddle...(!?)

Regards

**Comment by hbi99** [comment]
Since there is not response here, I am assuming you have solved your problem on your own. Hence, I'm closing this issue...re-open if you need my help.
