### ISSUE TITLE
JSON.search(object, query) fails if object changes

### ISSUE THREAD

**Issue by Alamantus** [hbi99/defiant.js#58]
I'm building an application that allows users to build a "dictionary", and I'm having the data save into a single JS object currentDictionary with each entry as an object in an array words within currentDictionary. I have a simple search box set up that works perfectly right up until I add a new word, which changes the currentDictionary object by inserting the new word into the words array. After adding the new word, the search no longer works.

Here is the code that runs whenever the search is executed:

```javascript
var searchResults = [];
if (document.getElementById("searchOptionWord").checked) {
    var wordNameSearch = JSON.search(currentDictionary, '//words[contains(name, "' + search + '")]/name');
    for (var i = 0; i < wordNameSearch.length; i++) {
        searchResults.push(wordNameSearch[i]);
    }
}
if (document.getElementById("searchOptionSimple").checked) {
    var simpleDefinitionSearch = JSON.search(currentDictionary, '//words[contains(simpleDefinition, "' + search + '")]/name');
    for (var i = 0; i < simpleDefinitionSearch.length; i++) {
        if (searchResults.indexOf(simpleDefinitionSearch[i]) < 0) {
            searchResults.push(simpleDefinitionSearch[i]);
        }
    }
}
if (document.getElementById("searchOptionLong").checked) {
    var longDefinitionSearch = JSON.search(currentDictionary, '//words[contains(longDefinition, "' + search + '")]/name');
    for (var i = 0; i < longDefinitionSearch.length; i++) {
        if (searchResults.indexOf(longDefinitionSearch[i]) < 0) {
            searchResults.push(longDefinitionSearch[i]);
        }
    }
}
```

It would make sense to me that JSON.search() should run anew on the target object each time it is executed, but since it fails after the target changes, it seems that this is not the case?

Is this a limitation of the JS Objects or of Defiant.js?

(tested in Chrome 46.0.2490.80 m and Firefox 40.0.3)

EDIT: Interestingly enough, I've found that if I remove a word instead of adding one to the words array, the search still works. I don't know what this necessarily means, but it does seem strange.

**Comment by Alamantus** [comment]
I discovered that the reason this was happening was because of the way I was adding new words. I had this:

```javascript
var Word = function (word, simpleDefinition, longDefinition, partOfSpeech) {
    this.name = word;
    this.simpleDefinition = simpleDefinition;
    this.longDefinition = longDefinition;
    this.partOfSpeech = partOfSpeech;
}
```
and I was trying to add words to my words array like this:
```javascript
currentDictionary.words.push(new Word(word, simpleDefinition, longDefinition, partOfSpeech));
```
which was messing up the way Defiant searches because technically a Word isn't a JSON object (or something like that).

I changed it to this:
```javascript
currentDictionary.words.push({name: word, simpleDefinition: simpleDefinition, longDefinition: longDefinition, partOfSpeech: partOfSpeech});
```
and the search works just fine after adding!

Sorry for the trouble.

**Comment by hbi99** [comment]
@Alamantus,
Great that you solved it on your own!

Here is an alternative suggestion to your code...the code below might need some adjustments, depending on how it looks on your end...though I think you might get that this is a cleaner approach and the code becomes easier to understand (hopefully :-)).

```javascript
var xpath = [];
    searchResults;

if (document.getElementById("searchOptionWord").checked) {
    xpath.push('contains(name, "'+ search +'")');
}
if (document.getElementById("searchOptionSimple").checked) {
    xpath.push('contains(simpleDefinition, "'+ search +'")');
}
if (document.getElementById("searchOptionLong").checked) {
    xpath.push('contains(longDefinition, "'+ search +'")');
}

searchResults = JSON.search(currentDictionary, '//words['+ xpath.join(' or ') +']/name');
```

**Comment by Alamantus** [comment]
That's much nicer than what I have! I didn't know about the or clauses.

Thanks for your help!
