### ISSUE TITLE
Cannot find JSON objects using properties with a hyphen

### ISSUE THREAD

**Issue by RevillWeb** [hbi99/defiant.js#60]
I'm not sure if this is a limitation to this library or with XPath itself, but I am unable to selected JSON objects based of a property if that property has a hyphen. For example `//*[item-type="event"]` wouldn't work.

Any help getting round this would be amazing!

Thank you.

**Comment by hbi99** [comment]
Hi @RevillWeb,
For the fast answer / solution, look at this fiddle:
http://jsfiddle.net/hbi99/fxv0b7p4/

To find out the reason for this XPath, check out my reply on this issue: https://github.com/hbi99/defiant.js/issues/56

Best regards
