### ISSUE TITLE
Issue with JSON's havin 'null' : Cannot read property of constructor null

### ISSUE THREAD

**Issue by SorrowfulBlinger** [hbi99/defiant.js#62]
{
    "fs": [
        {
            "directoryA": [
                {
                    "directoryB": "defiant.js"
                },
                {
                    "directoryC": [
                        "style.css",
                        "style.less"
                    ]
                },
                {
                    "directoryD": [
                        "logo.png",
                        "sprite.png"
                    ]
                },
                {
                    "directoryF": {
                        "subDirectoryF": [
                            null,
                            "a"
                        ]
                    }
                }
            ]
        },
        "readme.txt",
        "config.php",
        "index.htm"
    ]
}

If i run JSON.search(obj,'//fs') , it throws an error - 'TypeError: Cannot read property 'constructor' of undefined' . I believe this is because of the 'null' - under subDirectoryF.
PS : i am using the latest defiant.min.js

**Comment by hbi99** [comment]
@SorrowfulBlinger,
Thanks for the report. In version `1.3.5`, *null* values are handled correctly and does not throw error.

Cheers

**Comment by abbasovalex** [comment]
I have the same problem (v1.3.6)
You can see my data by link http://pastebin.com/HR1i26M2

**Comment by hbi99** [comment]
@abbasovalex,
I have isolated the problem...I am on it and will get back to you with the fix as soon as I solve it.

Thanks

**Comment by abbasovalex** [comment]
@hbi99 ok. If I undestood broblem raise when list is:
...
"prices": [null],
...

**Comment by hbi99** [comment]
@abbasovalex,
Can you please test this on your end:
https://raw.githubusercontent.com/hbi99/defiant.js/null-value-fix/dist/defiant.min.js

...I think this should solve the issue and as soon as you verify it, I'll merge it to the master branch.

Thanks in advance

**Comment by hbi99** [comment]
@abbasovalex,
I have tested and re-tested and this issue is now fixed in version v1.3.8
Please re-open if you do not agree.
