### ISSUE TITLE
Search not working fine when a key has an array of values 

### ISSUE THREAD

**Issue by SorrowfulBlinger** [hbi99/defiant.js#63]
var x = {
          "directoryD": [
            "spitelogo.png",
            "sprite.png"
          ],
    	"c" : "loss"
        };
y = JSON.search( x, '//*[contains(directoryD,"sprite")]' );
y returns '[]' i would expect a match since 'sprite.png' is a match.
Do you plan to have this functionality added anytime soon ?

PS : i am using the latest defiant.min.js

**Comment by hbi99** [comment]
@SorrowfulBlinger,
The XPath is faulty so here is a JSFiddle with the correct XPath:
http://jsfiddle.net/hbi99/1z9h0ovd/

PS: I think you might have wrong spell on "spitelogo.png". I have corrected it to "spritelogo.png".

**Comment by SorrowfulBlinger** [comment]
Great thanks .. i did not know about the text() attribute !
