### ISSUE TITLE
Return duplicate result in Safari browser

### ISSUE THREAD

**Issue by Kimleang** [hbi99/defiant.js#64]
please help, I use defiant.js in my project, and I notice it return duplicate result in safari browser.

![defiant - duplicate result](https://cloud.githubusercontent.com/assets/2344413/11450556/c910f136-95d6-11e5-9f0a-96ce9f2d8130.jpg)

**Comment by hbi99** [comment]
@Kimleang,
Can you please provide with further details...or complete / alter this JSFiddle to duplicate your problem:
http://jsfiddle.net/hbi99/bojd6emk/

When I test this fiddle in Chrome and Safari, the result is identical - DefiantJS finds only one match.

Cheers

**Comment by Kimleang** [comment]
@hbi99 thank you for your help, I have found the problem may not from DefiantJS.
When I test DefiantJS alone result is also identical, but I use DefiantJS with VueJS result is duplicate in Safari Browser both Mac and iOS, so I think problem may be from VueJS but I can't figure out the problem.
here is my sample to show the problem: https://dl.dropboxusercontent.com/u/28379308/defiant-test.zip

Thank.

**Comment by hbi99** [comment]
To tell you the truth, I am feeling a little bit lazy and will not troubleshoot VueJS...despite this, I do have a solution for you. I'd suggest that you use the snapshot feature of DefiantJS - it seems to work fine with VueJS and especially beneficial when dealing with large JSON data.

```javascript
	...
	ready: function(){
		var self = this;

		Defiant.getSnapshot(this.products, function(snapshot) {
			self.result = JSON.search(snapshot, '//*[color="Gold"]');
		});
	}
	...
```

**Comment by Kimleang** [comment]
big thanks for your help and suggestion, it work.

**Comment by srhise** [comment]
I can confirm I also have this issue in Safari. The example I have can't quite fit into a JSFiddle, as it's part of a larger app. I'll try. But I am using the snapshot feature and for a very unique case (one out of six parameters) I am getting 6 entries returned when there should be 3. 

I will see if I can produce a JSFiddle. But this breaks the vue.js template bindings. The issue does not seem to be specific to vue.js, however. I am debugging the return of the search function and do in fact see the duplicate items before they are passed back to vue. 

Let me see if I can get a JSFiddle of this up and running.

**Comment by srhise** [comment]
Here it is: https://jsfiddle.net/hbi99/bojd6emk/

**Comment by Kimleang** [comment]
@srhise I found the answer from the creator of VueJS. I think this may be related to search algorithm on DefiantJS as he mentions using ```for ... in``` to iterate over an Array. This is the wrong usage and not guaranteed to work consistently in different JavaScript engines.

And here is a link with much more discussion in it.
http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea

**Comment by srhise** [comment]
@Kimleang Anyway to fix it that you would know of? To be clear, it's DefiantJS that's using for ... in?

**Comment by Kimleang** [comment]
@srhise Yes, it just my opinion that I think DefiantJS using ```for ... in``` somewhere in search algorithm to iterate over and Array.
Here is another example using ```for ... in``` to iterate over an Array and cause duplicate result in Safari Browser. http://jsfiddle.net/amanpatel/1gxhL4Lv/2/ and if you change the code from ```for ... in``` to ``` for (...; ...; ...;)``` there is no duplicate result in Safari.

currently I'm temporary using @hbi99 suggestion to fixed this problem
```javascript
 ...
    ready: function(){
        var self = this;

        Defiant.getSnapshot(this.products, function(snapshot) {
            self.result = JSON.search(snapshot, '//*[color="Gold"]');
        });
    }
...
```

**Comment by hbi99** [comment]
I'll investigate this later today....though it feels weird that DefiantJS on its own does not result on duplicate matches. For instance, this fiddle behaves and results identical in both Chrome and Safari :unamused: :
http://jsfiddle.net/sos1ep09/17/

...despite the fact that ```for...in``` is used. Logically this means that VueJS is introducing something to the environment that is not there by-default.

**Comment by hbi99** [comment]
@Kimleang and @srhise,
I have made a few adjustments and created the "safari-fix" branch. If both of you can verify that it works on your end as well, I will merge this to master branch.

Cheers

**Comment by Kimleang** [comment]
@hbi99 I really appreciate your time and help.
I can confirm this fix is working, there is no duplicate result in safari anymore.

Big Thank!
