### ISSUE TITLE
Searching where key contains a number

### ISSUE THREAD

**Issue by mpnieland** [hbi99/defiant.js#69]
I can't seem to find out how this is done.

For example, I have a json object where the key is 2016010301.  Yet doing something like JSON.search(data, '//2016010301') yields an error.  I also have objects like so: 00-0029701 that do not work either.  Is this possible with defiant or is there a problem with nubmers in the XPath?

**Comment by hbi99** [comment]
Hi @mpnieland,
Check out these two issues:
https://github.com/hbi99/defiant.js/issues/60
https://github.com/hbi99/defiant.js/issues/56

They are explained with JSFiddles - tell me if you still need help.

Regards

**Comment by hbi99** [comment]
@mpnieland,
Since you have not replied, I am assuming my comment has helped you and you've solved your problem.
Therefore, I am closing this issue...re-open if you need further assistance.

Cheers
