### ISSUE TITLE
Does not accept multiple attributes as input

### ISSUE THREAD

**Issue by vishnusv99** [hbi99/defiant.js#73]
The XPath does not accept multiple attributes as input.
For example, "//*[contains(@*, "fiction")]" --- This does not search all attributes regardless of name in the below example.
//*[contains(category, "fiction")] ----- This works since we are explicitly mentioning attribute name.
But if we want to search all the attributes regardless of name, then what is the option?
{
   "store": {
      "book": [
         {
            "title": "Sword of Honour",
            "category": "fiction",
            "author": "Evelyn Waugh",
            "@price": 12.99
         },
         {
            "title": "Moby Dick",
            "category": "fiction",
            "author": "Herman Melville",
            "isbn": "0-553-21311-3",
            "@price": 8.99
         },
         {
            "title": "Sayings of the Century",
            "category": "reference",
            "author": "Nigel Rees",
            "@price": 8.95
         },
         {
            "title": "The Lord of the Rings",
            "category": "fiction",
            "author": "J. R. R. Tolkien",
            "isbn": "0-395-19395-8",
            "@price": 22.99
         }
      ],
      "bicycle": {
         "brand": "Cannondale",
         "color": "red",
         "@price": 19.95
      }
   }
}

**Comment by hbi99** [comment]
@vishnusv99,
I think you are looking for an XPath expression like this:
```
//book[contains(., "fic")]
```
The 'dot' is the wildcard you are looking for...but notice that I start the expression with "//book" and not "//*". The reason for this narrowing is that we are avoiding unnecessary matches this way.
I hope this helps

(open the issue if you want continued support)
