### ISSUE TITLE
Not searching value containing brackets and capital letters

### ISSUE THREAD

**Issue by rahulraveendranath** [hbi99/defiant.js#77]
Hi,

I am trying to search json with  brackets and capital letters values. Its failing to search a value with capital letter and set of brackets in it.

Sample data and test case is given below
here is my json and the test cases. I would really appreciate your help.
var data = {
      "items": [
         {
            "eVal": "Value In (dollars)",
            "status": "open"
         },
         {
            "eVal": "value in (yen)",
            "status": "closed"
         }
      ]
   },
if I search with following search criteria it works fine
   found = JSON.search(data, '//*[contains(eVal,"value in (yen)") ]');
But when I use the one below I am not getting any result.
   found = JSON.search(data, '//*[contains(eVal,"Value In (dollars)") ]');

**Comment by hbi99** [comment]
Hi @rahulraveendranath,
I just tried to query your JSON in the XPath Evaluator here:
http://www.defiantjs.com/

...as I can see, you are missing an asterisk sign like this. I found a minor problem and fixed this. The latest version of this lib, both of the queries below works fine.
`//*[contains(eVal,"value in (yen)")]`
`//*[contains(eVal,"Value in (dollars)")]`

Cheers
