### ISSUE TITLE
Not available on WebJars?

### ISSUE THREAD

**Issue by Jhara** [hbi99/defiant.js#78]
Cannot find this module on webJars

http://www.webjars.org/documentation

**Comment by hbi99** [comment]
Hi @Jhara,
I made a WebJar request...
I guess I'll join the Jarhead Clan now

![Jarhead Clan](https://media.giphy.com/media/WNbVg64u5sZ1u/giphy.gif)

**Comment by Jhara** [comment]
Closed!!

Here is the new WebJar: https://github.com/webjars/defiant.js

https://github.com/webjars/webjars/issues/1414
