### ISSUE TITLE
How to pass a dynamic variable JSON.Search function

### ISSUE THREAD

**Issue by punit07** [hbi99/defiant.js#81]
Hi there,

I have a form, where user enter a string/keyword to query. I want to pass this keyword to this function ...
I have tried something like this  ....
```
var cname = $("#name").val();
var reds = JSON.search(myjson, '//*[contains(courseName, cname)]');
```
but its not working. 

Can you please advise how do I pass a **dynamic** variable to the JSON.search function ?

Thanks

**Comment by hakan-peltarion** [comment]
Hi Punit,
Sorry for late response...I've been focusing coding on AI and Deep Learning - thus shutting off everything else :-S

You can do something like this:
```js
var cname = $("#name").val();
var reds = JSON.search(myjson, '//*[contains(courseName, "'+ cname +'")]');
```

Cheers
