### ISSUE TITLE
Error in web worker using importScripts(defiant.min.js)

### ISSUE THREAD

**Issue by kskoeldMW** [hbi99/defiant.js#83]
I'm trying to use defiant.js in a web worker, since I'm doing heavy computation in addition to the JSON.search.
However I keep getting a 

> Uncaught Error: Uncaught ReferenceError: Defiant is not defined

I created a simple example using part of the demo code.
[Archive.zip](https://github.com/hbi99/defiant.js/files/953325/Archive.zip)

**Comment by hbi99** [comment]
Hi @kskoeldMW,
There is already support for web workers in Defiant.js
Look at the code below...also, you should yse the latest version - which 1.4.2.

Kind regards

```html
<script src="defiant.min.js"></script>
<script>

var obj = {
	"car": [
		{"id": 10, "color": "silver", "name": "Volvo"},
		{"id": 11, "color": "red",    "name": "Saab"},
		{"id": 12, "color": "red",    "name": "Peugeot"},
		{"id": 13, "color": "yellow", "name": "Porsche"}
	],
	"bike": [
		{"id": 20, "color": "black", "name": "Cannondale"},
		{"id": 21, "color": "red",   "name": "Shimano"}
	]
};

Defiant.getSnapshot(obj, function(snapshot) {
    var found = JSON.search(snapshot, '//car');
    console.log(found);
});
	
</script>
```

**Comment by kskoeldMW** [comment]
Hi @hbi99 
I know of the getSnapshot option, but unless I have misunderstood some fundamental things about it it doesn't give me access to defiant from within my own web-worker.
I can execute the Snapshot in the main thread and then post the result to my web-worker, however the large JSON (5-15mb) is handled only in the web-worker. I would have to pass it over to the main thread, run the Snapshot (which is executed in another web-worker) and then pass the result back to my WW.
Since I'm using the JSON.search quite often that would induce a lot of unnecessary overhead on the main thread. 
So is there a way to access the defiant functionality directly within a web-worker?

**Comment by hbi99** [comment]
No...you can not access Defiant from within a web worker. I'd recommend that you look into the types of objects / scripts you can access into a web worker...defiant is not on of them.

**Comment by kskoeldMW** [comment]
Ok thanks - too bad, since I really like the ease-of-use and speed of defiant.
Oh well, than I have to look for another solution.

**Comment by hbi99** [comment]
I wonder if you should familiarise with web workers...messaging to and from a ww-thread is limited.

Anywho...good luck

**Comment by kskoeldMW** [comment]
Yes, thats exactly why doing that would not be a wise decision :)
Thanks for your precious time though ;)
