### ISSUE TITLE
i need for npm, using in nodejs

### ISSUE THREAD

**Issue by sajadghobadi** [hbi99/defiant.js#84]
thnaks for your nice library
but very people need this package on nodejs..
please bring it to nodejs too

**Comment by liangchunn** [comment]
Duplicate. Please look at issue #4

**Comment by hbi99** [comment]
Hi guys, just found a package that might enable support of DefiantJS in Node environment. I am looking in to this and will notify if I am successful.

**Comment by hbi99** [comment]
Whoever published this library on NPM - can you please release the name? I would like to publish it under my own account, as I am working on the node-version of this lib.

Thanks in advance

**Comment by hbi99** [comment]
Ok...because of the NPM troll, I've renamed this library and published it at:
https://www.npmjs.com/package/defiant.js

...notice that the trolls publishing will not be updated from now on; meaning deprecated:
https://www.npmjs.com/package/defiant

**Comment by sloanlance** [comment]
Have you tried contacting npm admins about the troll?  See: https://www.npmjs.com/policies/disputes

I've installed defiant.js in my project with the command `npm install defiant.js --save`.  It was successful and I can see it in the `node_modules` directory.

However, when I try to require it in my program, it always fails.  I've tried `require('defiant')`, `require('defiant.js')`, `require('defiantjs')`, but they all give the error:

```txt
Error: Cannot find module 'defiant'
```

Followed by a stack dump.  What's the correct way to use defiant?

**Comment by afharo** [comment]
Same issue for me :(
Is there anyway to make it work in NodeJS?

**Comment by afharo** [comment]
Found that changing "main" in package.json from "./lib/defiant" (that folder doesn't exist) to "./dist/defiant" or "./src/defiant", makes it load... although it fails because of `ReferenceError: navigator is not defined` at `dist/defiant.js:160:38`

**Comment by Arun4D** [comment]
I am also getting the `ReferenceError: navigator is not defined at dist/defiant.js:160:38`. 
Is there any way to make it work in NodeJS???

**Comment by hbi99** [comment]
This issue should be resolved with the support of node in `v2.0.0`
