### ISSUE TITLE
npm ERR! missing x10@git...

### ISSUE THREAD

**Issue by SGbo** [hbi99/defiant.js#88]
I tried installing the library via npm, but when I check `npm ls` the following error occurs:

`npm ERR! missing: x10@git://github.com/hbi99/x10.js.git, required by defiant.js@1.4.3
`

**Comment by sloanlance** [comment]
I don't understand why this error wasn't reported by npm when installing defiant.js.

**Comment by hbi99** [comment]
In version `v2.2.0` this will no longer be an issue
