### ISSUE TITLE
Defiant introduces an export bug to other dependencies in a browser project

### ISSUE THREAD

**Issue by StefanDimov** [hbi99/defiant.js#90]
I'm working on a project with an older version of Defiant but I can see that the problem in the current version as well.

Where ever Defiant or other modules are exported the code is something as follows:
`window.Defiant = module.exports = Defiant;`

This breaks other dependencies which check if `module`  is defined and if so only do a CommonJS export.

**Comment by hbi99** [comment]
Great input @StefanDimov,
Could you make a pull request with your suggestion?

Thanks in advance

**Comment by hbi99** [comment]
@StefanDimov please provide example code - re-open this issue when you do so.
