### ISSUE TITLE
Cannot find name Defiant

### ISSUE THREAD

**Issue by xProgrammer-007** [hbi99/defiant.js#93]
installed using `npm install --save defiant.js` and i am working in ionic app . It throws cannot find modules , tried all way but does not seem to work . 
How do i import the Defiant in my component

**Comment by hbi99** [comment]
I suspect you are trying to use Defiant in Node environment - you can't. It only works in browser only...currently. I am hoping to make it work in Node eventually.

**Comment by xProgrammer-007** [comment]
I just wanted the Snapshot and search functions , If you could provide me with some idea or code on how to implement this two in my component module . if so .. Or i would be glad if you suggest me with other good libraries that searches through JSON

**Comment by hbi99** [comment]
Do you mean in browser?
If yes, you can test this lib at: http://www.defiantjs.com/

If in Node environment, look at these alternatives:
https://github.com/search?l=JavaScript&o=desc&q=json+search&s=stars&type=Repositories&utf8=%E2%9C%93

Kind regards,
Hakan
