### ISSUE TITLE
XPATH Query 

### ISSUE THREAD

**Issue by Houtheyfa** [hbi99/defiant.js#96]
I would like to performe a search on JSON tree in wich i extract an array of unique values.

I used the following Query but it won't work :cry:  

JSON.search(data ,  " **distinct-values(//title )** ");  

Would you help me please !

**Comment by hbi99** [comment]
Hey, so I solved your problem with this XPath:
```
//book/title[not(preceding::book/title/. = .)]
```
This XPath will ensure that the selected titles are distinct.
