### ISSUE TITLE
XPath select children

### ISSUE THREAD

**Issue by tristancaron** [hbi99/defiant.js#97]
Hello,

On the XPATH EVALUATOR, I am trying to use `/store/book`, but it does not return anything. It should return the list of books.

**Comment by hbi99** [comment]
Hi @tristancaron,
Try ```//store/book```...i.e. the double slash in the beginning (recursive descent) will make sure to find "store" first and then all the book items directly beneath it. Even though your expression is correct if you look at the structure from JSON point of view - the XPath and the XML p.o.v. differs.
