### ISSUE TITLE
Problem with JSON search

### ISSUE THREAD

**Issue by rahulkr7010** [hbi99/defiant.js#98]
I want to get objects of 'heading = "GROUP"' from an array of objects. Where array contains the different type of objects. But the search is not working as expected. I have made Stackblitz for this problem. Please check this issue.
The link is given below: 
https://stackblitz.com/edit/angular-heyrs9?file=src/app/app.component.ts

**Comment by TuiTeamSearch** [comment]
Hi @rahulkr7010,
I suspect the problem is these rows:
```
    let gp = new Group();
    gp.id = 1;
    gp.heading = "GROUP";
    this.list.push(gp);
```
...because if you add objects like this to your array, Defiant can find the matches:
```
    this.list.push({id:1, heading: 'GROUP'});
    this.list.push({id:1, heading: 'GROUP'});
    this.list.push({id:1, heading: 'GROUP'});
```

I hope this helps you when debugging.
Kind regards,
Hakan

**Comment by hbi99** [comment]
Hi @rahulkr7010,
I suspect the problem is these rows:
```
    let gp = new Group();
    gp.id = 1;
    gp.heading = "GROUP";
    this.list.push(gp);
```
...because if you add objects like this to your array, Defiant can find the matches:
```
    this.list.push({id:1, heading: 'GROUP'});
    this.list.push({id:1, heading: 'GROUP'});
    this.list.push({id:1, heading: 'GROUP'});
```
I hope this helps you when debugging.
Kind regards,
Hakan

**Comment by rahulkr7010** [comment]
Thanks for your reply and Thanks for the defiantJs.
