### ISSUE TITLE
return the index of the results

### ISSUE THREAD

**Issue by mejuliver** [hbi99/defiant.js#99]
is there a way I could get the index of the return results? this

`JSON.search($data, '//*[contains(keyword, "digital")]');`

returns only the found item. Any ideas, help please?

**Comment by hbi99** [comment]
Hi @mejuliver,
I guess you mean the index of the found item in its position among its siblings (and related information). This is currently not supported but I am thinking about it. I'll get back to you if/when it will be implemented.
